### ISSUE TITLE
Localizations

### ISSUE THREAD

**Issue by maniyax** [ShubhamJain7/imageCaptioning-NVDA-Addon#1]
Hello!

Tell me please, will you create localization system?

I'm going to translate your addon on russian language.

**Comment by ShubhamJain7** [comment]
Hi!

The captions generated from the model are not deterministic so it isn't possible to add translations directly. The vocab file (A file containing all the words the model can use) can be translated but the model has been trained to form sentences in English so even if you translate the vocab file to Russian, the generated caption might not have the right grammar.
I suppose the best one can do is use an online API for translation once the English caption is available.

Regards,
Shubham Jain

**Comment by maniyax** [comment]
Okay, i understand you.

**Comment by maniyax** [comment]
Okay, i understand you.
